version: 2.1
jobs:
  build:
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update
      - run: ccmake . 
      - run: make
      - run: ./RandomNumberInterface
