version: 2.1
jobs:
  build:
    docker:
      - image: madduci/docker-linux-cpp
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update
      - run: apt-get install -y cmake
      - run: ccmake . 
      - run: make
      - run: ./RandomNumberInterface
